"""Add on_hand, allocated, on_order quantities in Inventory model

Revision ID: 0bbdeaa10242
Revises: 27344188795f
Create Date: 2026-07-23 21:35:36.397843

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0bbdeaa10242"
down_revision: str | Sequence[str] | None = "27344188795f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("inventory", sa.Column("quantity_on_hand", sa.Integer(), server_default="0", nullable=False))
    op.add_column("inventory", sa.Column("quantity_allocated", sa.Integer(), server_default="0", nullable=False))
    op.add_column("inventory", sa.Column("quantity_on_order", sa.Integer(), server_default="0", nullable=False))
    op.drop_column("inventory", "quantity_available")
    # ### end Alembic commands ###

    # Manually add the check constraints here:
    op.create_check_constraint("chk_inventory_allocated_positive", "inventory", sa.text("quantity_allocated >= 0"))
    op.create_check_constraint("chk_inventory_on_order_positive", "inventory", sa.text("quantity_on_order >= 0"))
    op.create_check_constraint("chk_inventory_on_hand_positive", "inventory", sa.text("quantity_on_hand >= 0"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop constraints first during downgrade
    op.drop_constraint("chk_inventory_on_order_positive", "inventory", type_="check")
    op.drop_constraint("chk_inventory_on_hand_positive", "inventory", type_="check")
    op.drop_constraint("chk_inventory_allocated_positive", "inventory", type_="check")

    op.add_column(
        "inventory",
        sa.Column("quantity_available", sa.INTEGER(), server_default=sa.text("0"), autoincrement=False, nullable=False),
    )
    op.drop_column("inventory", "quantity_on_order")
    op.drop_column("inventory", "quantity_allocated")
    op.drop_column("inventory", "quantity_on_hand")
    # ### end Alembic commands ###
