"""Adding the pricing models for the charging strategy

Revision ID: 4c4b90f24170
Revises: a3a04c15950b
Create Date: 2026-06-22 17:21:31.586744

"""
import uuid
from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4c4b90f24170'
down_revision: str | Sequence[str] | None = 'a3a04c15950b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_plans',
    sa.Column('name', sa.Enum('GROWTH', 'PRO', 'ENTERPRISE', 'CUSTOM', name='planname'), nullable=False),
    sa.Column('listings_limit', sa.Integer(), nullable=False),
    sa.Column('api_limit', sa.Integer(), nullable=False),
    sa.Column('price_monthly', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_plans_id'), 'pricing_plans', ['id'], unique=False)
    op.create_table('pricing_subscriptions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['pricing_plans.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_subscriptions_id'), 'pricing_subscriptions', ['id'], unique=False)
    op.create_index(
        op.f('ix_pricing_subscriptions_workspace_id'), 'pricing_subscriptions', ['workspace_id'], unique=False)
    op.create_table('pricing_usage',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('listings_count', sa.Integer(), nullable=False),
    sa.Column('api_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_usage_id'), 'pricing_usage', ['id'], unique=False)
    op.create_index(op.f('ix_pricing_usage_workspace_id'), 'pricing_usage', ['workspace_id'], unique=False)
    # ### end Alembic commands ###

    # 1. Define the table reference for the bulk insert
    pricing_plans = sa.table(
        'pricing_plans',
        sa.column('id', sa.Uuid),
        sa.column('name', sa.String),
        sa.column('listings_limit', sa.Integer),
        sa.column('api_limit', sa.Integer),
        sa.column('price_monthly', sa.Integer),
        sa.column('created_at', sa.DateTime),
        sa.column('updated_at', sa.DateTime),
        sa.column('is_deleted', sa.Boolean),
    )

    # 2. Define your seed data
    # Tip: Use static UUIDs so the IDs are the same across all environments
    now = datetime.now(UTC)

    op.bulk_insert(
        pricing_plans,
        [
            {
                "id": uuid.UUID("550e8400-e29b-41d4-a716-446655440000"),
                "name": "GROWTH",
                "listings_limit": 2500,
                "api_limit": 250000,
                "price_monthly": 49,
                "created_at": now,
                "updated_at": now,
                "is_deleted": False,
            },
            {
                "id": uuid.UUID("6ba7b810-9dad-11d1-80b4-00c04fd430c8"),
                "name": "PRO",
                "listings_limit": 10000,
                "api_limit": 1500000,
                "price_monthly": 99,
                "created_at": now,
                "updated_at": now,
                "is_deleted": False,
            },
            {
                "id": uuid.UUID("7d444840-9dc0-11d1-b245-5ffdce74fad2"),
                "name": "ENTERPRISE",
                "listings_limit": 50000,
                "api_limit": 10000000,
                "price_monthly": 299,
                "created_at": now,
                "updated_at": now,
                "is_deleted": False,
            },
        ]
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pricing_usage_workspace_id'), table_name='pricing_usage')
    op.drop_index(op.f('ix_pricing_usage_id'), table_name='pricing_usage')
    op.drop_table('pricing_usage')
    op.drop_index(op.f('ix_pricing_subscriptions_workspace_id'), table_name='pricing_subscriptions')
    op.drop_index(op.f('ix_pricing_subscriptions_id'), table_name='pricing_subscriptions')
    op.drop_table('pricing_subscriptions')
    op.drop_index(op.f('ix_pricing_plans_id'), table_name='pricing_plans')
    op.drop_table('pricing_plans')
    # ### end Alembic commands ###
