"""Add first, last name and make email unique per workspace in Customer model

Revision ID: 7747fc424c52
Revises: d8d6774af884
Create Date: 2026-07-05 22:10:10.453346

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7747fc424c52"
down_revision: str | Sequence[str] | None = "d8d6774af884"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("customers", sa.Column("first_name", sa.String(length=255), nullable=False))
    op.add_column("customers", sa.Column("last_name", sa.String(length=255), nullable=True))
    op.alter_column("customers", "email", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.create_unique_constraint("uix_workspace_customer_email", "customers", ["workspace_id", "email"])
    op.drop_column("customers", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("customers", sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint("uix_workspace_customer_email", "customers", type_="unique")
    op.alter_column("customers", "email", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.drop_column("customers", "last_name")
    op.drop_column("customers", "first_name")
    # ### end Alembic commands ###
