"""Supplier uniq constraint on workspace, email

Revision ID: 86c3f1d539be
Revises: 7747fc424c52
Create Date: 2026-07-08 17:50:30.010363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c3f1d539be'
down_revision: Union[str, Sequence[str], None] = '7747fc424c52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_suppliers_email'), 'suppliers', ['email'], unique=False)
    op.create_unique_constraint('uix_workspace_supplier_email', 'suppliers', ['workspace_id', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_workspace_supplier_email', 'suppliers', type_='unique')
    op.drop_index(op.f('ix_suppliers_email'), table_name='suppliers')
    # ### end Alembic commands ###
