"""Drop EbayItem table

Revision ID: c43109fd3a90
Revises: 37cbf0d0de34
Create Date: 2026-08-13 13:07:54.190953

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c43109fd3a90"
down_revision: str | Sequence[str] | None = "37cbf0d0de34"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ebay_items_external_id"), table_name="ebay_items")
    op.drop_index(op.f("ix_ebay_items_id"), table_name="ebay_items")
    op.drop_index(op.f("ix_ebay_items_sku"), table_name="ebay_items")
    op.drop_index(op.f("ix_ebay_items_status"), table_name="ebay_items")
    op.drop_index(op.f("ix_ebay_items_workspace_id"), table_name="ebay_items")
    op.drop_table("ebay_items")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ebay_items",
        sa.Column("workspace_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("external_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("sku", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("price", sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
        sa.Column("currency", sa.VARCHAR(length=3), autoincrement=False, nullable=False),
        sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("images", postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], name=op.f("ebay_items_workspace_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("ebay_items_pkey")),
        sa.UniqueConstraint(
            "workspace_id",
            "external_id",
            name=op.f("uq_workspace_ebay_external_id"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("ix_ebay_items_workspace_id"), "ebay_items", ["workspace_id"], unique=False)
    op.create_index(op.f("ix_ebay_items_status"), "ebay_items", ["status"], unique=False)
    op.create_index(op.f("ix_ebay_items_sku"), "ebay_items", ["sku"], unique=False)
    op.create_index(op.f("ix_ebay_items_id"), "ebay_items", ["id"], unique=False)
    op.create_index(op.f("ix_ebay_items_external_id"), "ebay_items", ["external_id"], unique=False)
    # ### end Alembic commands ###
