"""Unique constraints for po and so models

Revision ID: 27344188795f
Revises: 86c3f1d539be
Create Date: 2026-07-16 19:36:13.224607

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27344188795f"
down_revision: str | Sequence[str] | None = "86c3f1d539be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_purchase_orders_workspace_po_number", "purchase_orders", ["workspace_id", "po_number"]
    )
    op.add_column("sell_order_lines", sa.Column("sell_order_id", sa.Uuid(), nullable=False))
    op.add_column("sell_order_lines", sa.Column("unit_cost", sa.Integer(), nullable=False))
    op.drop_index(op.f("ix_sell_order_lines_order_id"), table_name="sell_order_lines")
    op.create_index(op.f("ix_sell_order_lines_sell_order_id"), "sell_order_lines", ["sell_order_id"], unique=False)
    op.drop_constraint(op.f("sell_order_lines_order_id_fkey"), "sell_order_lines", type_="foreignkey")
    op.create_foreign_key(None, "sell_order_lines", "sell_orders", ["sell_order_id"], ["id"])
    op.drop_column("sell_order_lines", "unit_price")
    op.drop_column("sell_order_lines", "order_id")
    op.add_column("sell_orders", sa.Column("so_number", sa.String(length=100), nullable=False))
    op.drop_index(op.f("ix_sell_orders_order_number"), table_name="sell_orders")
    op.create_index(op.f("ix_sell_orders_so_number"), "sell_orders", ["so_number"], unique=False)
    op.create_unique_constraint("uq_sell_orders_workspace_so_number", "sell_orders", ["workspace_id", "so_number"])
    op.drop_column("sell_orders", "order_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sell_orders", sa.Column("order_number", sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint("uq_sell_orders_workspace_so_number", "sell_orders", type_="unique")
    op.drop_index(op.f("ix_sell_orders_so_number"), table_name="sell_orders")
    op.create_index(op.f("ix_sell_orders_order_number"), "sell_orders", ["order_number"], unique=False)
    op.drop_column("sell_orders", "so_number")
    op.add_column("sell_order_lines", sa.Column("order_id", sa.UUID(), autoincrement=False, nullable=False))
    op.add_column("sell_order_lines", sa.Column("unit_price", sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "sell_order_lines", type_="foreignkey")
    op.create_foreign_key(
        op.f("sell_order_lines_order_id_fkey"), "sell_order_lines", "sell_orders", ["order_id"], ["id"]
    )
    op.drop_index(op.f("ix_sell_order_lines_sell_order_id"), table_name="sell_order_lines")
    op.create_index(op.f("ix_sell_order_lines_order_id"), "sell_order_lines", ["order_id"], unique=False)
    op.drop_column("sell_order_lines", "unit_cost")
    op.drop_column("sell_order_lines", "sell_order_id")
    op.drop_constraint("uq_purchase_orders_workspace_po_number", "purchase_orders", type_="unique")
    # ### end Alembic commands ###
