"""Add last_email_change_sent_at in User model

Revision ID: 2aa63e375a05
Revises: e54275bb318d
Create Date: 2026-10-09 23:12:25.430861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa63e375a05'
down_revision: Union[str, Sequence[str], None] = 'e54275bb318d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_email_change_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_email_change_sent_at')
    # ### end Alembic commands ###
