"""Remove integartion table and relationships

Revision ID: 37cbf0d0de34
Revises: 0bbdeaa10242
Create Date: 2026-08-13 13:00:41.659452

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "37cbf0d0de34"
down_revision: str | Sequence[str] | None = "0bbdeaa10242"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workspace_integrations_id"), table_name="workspace_integrations")
    op.drop_index(op.f("ix_workspace_integrations_workspace_id"), table_name="workspace_integrations")
    op.drop_table("workspace_integrations")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspace_integrations",
        sa.Column("workspace_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("provider_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("credentials", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], name=op.f("workspace_integrations_workspace_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("workspace_integrations_pkey")),
        sa.UniqueConstraint(
            "workspace_id",
            "provider_type",
            name=op.f("uq_workspace_provider"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_workspace_integrations_workspace_id"), "workspace_integrations", ["workspace_id"], unique=False
    )
    op.create_index(op.f("ix_workspace_integrations_id"), "workspace_integrations", ["id"], unique=False)
    # ### end Alembic commands ###
