"""Added global search index and customer  embeddings

Revision ID: 3be9370467af
Revises: e5a9975223ce
Create Date: 2026-09-04 16:45:48.909630

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import Vector

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be9370467af'
down_revision: Union[str, Sequence[str], None] = 'e5a9975223ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('global_search_index',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('CUSTOMER', 'SUPPLIER', 'ITEM', 'SELL_ORDER', 'INVENTORY', 'STOCK_MOVEMENT', name='entitytypeenum', native_enum=False, length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('snippet', sa.String(length=500), nullable=True),
    sa.Column('embedding', Vector(dim=768), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'entity_type', 'entity_id', name='uix_workspace_entity')
    )
    op.create_index(op.f('ix_global_search_index_entity_id'), 'global_search_index', ['entity_id'], unique=False)
    op.create_index(op.f('ix_global_search_index_id'), 'global_search_index', ['id'], unique=False)
    op.create_index(op.f('ix_global_search_index_workspace_id'), 'global_search_index', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_global_search_index_workspace_id'), table_name='global_search_index')
    op.drop_index(op.f('ix_global_search_index_id'), table_name='global_search_index')
    op.drop_index(op.f('ix_global_search_index_entity_id'), table_name='global_search_index')
    op.drop_table('global_search_index')
    # ### end Alembic commands ###
