"""Add item.barcode_id new file in Item model

Revision ID: 67542c075f23
Revises: 9a66eb97d048
Create Date: 2026-10-02 19:21:21.268604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67542c075f23'
down_revision: Union[str, Sequence[str], None] = '9a66eb97d048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('barcode_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'barcode_id')
    # ### end Alembic commands ###
