"""API usage now records user.id

Revision ID: 9a66eb97d048
Revises: d32d6a59df45
Create Date: 2026-10-02 11:52:05.422061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a66eb97d048'
down_revision: Union[str, Sequence[str], None] = 'd32d6a59df45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing_usage', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'pricing_usage', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pricing_usage', type_='foreignkey')
    op.drop_column('pricing_usage', 'user_id')
    # ### end Alembic commands ###
