"""Pricing strategy changed in order to support mid month plan changes

Revision ID: b8d127621c97
Revises: a3a04c15950b
Create Date: 2026-06-23 12:02:18.344835

"""

import uuid
from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8d127621c97"
down_revision: str | Sequence[str] | None = "a3a04c15950b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pricing_plans",
        sa.Column("name", sa.Enum("GROWTH", "PRO", "ENTERPRISE", "CUSTOM", name="planname"), nullable=False),
        sa.Column("listings_limit", sa.Integer(), nullable=False),
        sa.Column("api_limit", sa.Integer(), nullable=False),
        sa.Column("price_monthly", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pricing_plans_id"), "pricing_plans", ["id"], unique=False)
    op.create_table(
        "pricing_subscriptions",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_paused", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["pricing_plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pricing_subscriptions_id"), "pricing_subscriptions", ["id"], unique=False)
    op.create_index(
        "uq_active_subscription_per_workspace",
        "pricing_subscriptions",
        ["workspace_id"],
        unique=True,
        postgresql_where=sa.text("is_active = true"),
    )
    op.create_table(
        "pricing_usage",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("metric_type", sa.Enum("API_REQUEST", "LISTING", name="metrictype"), nullable=False),
        sa.Column("request_type", sa.Enum("GET", "POST", "PUT", "PATCH", "DELETE", name="httpmethod"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["pricing_plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pricing_usage_id"), "pricing_usage", ["id"], unique=False)
    op.create_index(
        "ix_usage_workspace_plan_date", "pricing_usage", ["workspace_id", "plan_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###
    # 2. Define seed data

    pricing_plans_table = sa.table(
        "pricing_plans",
        sa.column("id", sa.Uuid()),
        sa.column("name", sa.String()),
        sa.column("listings_limit", sa.Integer()),
        sa.column("api_limit", sa.Integer()),
        sa.column("price_monthly", sa.Integer()),
        sa.column("created_at", sa.DateTime()),
        sa.column("updated_at", sa.DateTime()),
        sa.column("is_deleted", sa.Boolean()),
    )

    now = datetime.now(UTC)

    op.bulk_insert(
        pricing_plans_table,
        [
            {
                "id": uuid.UUID("550e8400-e29b-41d4-a716-446655440000"),
                "name": "GROWTH",
                "listings_limit": 2500,
                "api_limit": 250000,
                "price_monthly": 49,
                "created_at": now,
                "updated_at": now,
                "is_deleted": False,
            },
            {
                "id": uuid.UUID("6ba7b810-9dad-11d1-80b4-00c04fd430c8"),
                "name": "PRO",
                "listings_limit": 10000,
                "api_limit": 1500000,
                "price_monthly": 99,
                "created_at": now,
                "updated_at": now,
                "is_deleted": False,
            },
            {
                "id": uuid.UUID("7d444840-9dc0-11d1-b245-5ffdce74fad2"),
                "name": "ENTERPRISE",
                "listings_limit": 50000,
                "api_limit": 10000000,
                "price_monthly": 299,
                "created_at": now,
                "updated_at": now,
                "is_deleted": False,
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_usage_workspace_plan_date", table_name="pricing_usage")
    op.drop_index(op.f("ix_pricing_usage_id"), table_name="pricing_usage")
    op.drop_table("pricing_usage")
    op.drop_index(
        "uq_active_subscription_per_workspace",
        table_name="pricing_subscriptions",
        postgresql_where=sa.text("is_active = true"),
    )
    op.drop_index(op.f("ix_pricing_subscriptions_id"), table_name="pricing_subscriptions")
    op.drop_table("pricing_subscriptions")
    op.drop_index(op.f("ix_pricing_plans_id"), table_name="pricing_plans")
    op.drop_table("pricing_plans")
    # ### end Alembic commands ###
