"""Password reset func and User migrations

Revision ID: d32d6a59df45
Revises: 9390410ca880
Create Date: 2026-09-29 12:45:49.334125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd32d6a59df45'
down_revision: Union[str, Sequence[str], None] = '9390410ca880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_password_reset_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_password_reset_sent_at')
    # ### end Alembic commands ###
