"""WorkspaceUserNote table & API CRUD operations added

Revision ID: d8a74429950e
Revises: c43109fd3a90
Create Date: 2026-08-21 14:05:40.936884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a74429950e'
down_revision: Union[str, Sequence[str], None] = 'c43109fd3a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_user_notes',
    sa.Column('workspace_user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_user_id'], ['workspace_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_user_notes_id'), 'workspace_user_notes', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_user_notes_workspace_user_id'), 'workspace_user_notes', ['workspace_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_user_notes_workspace_user_id'), table_name='workspace_user_notes')
    op.drop_index(op.f('ix_workspace_user_notes_id'), table_name='workspace_user_notes')
    op.drop_table('workspace_user_notes')
    # ### end Alembic commands ###
