"""Added is_deleted in base model + Added ERP base models

Revision ID: d8d6774af884
Revises: b8d127621c97
Create Date: 2026-07-05 13:59:56.876724

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d8d6774af884"
down_revision: str | Sequence[str] | None = "b8d127621c97"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_customers_email"), "customers", ["email"], unique=False)
    op.create_index(op.f("ix_customers_id"), "customers", ["id"], unique=False)
    op.create_index(op.f("ix_customers_workspace_id"), "customers", ["workspace_id"], unique=False)
    op.create_table(
        "items",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("base_price", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "sku", name="uix_workspace_sku"),
    )
    op.create_index(op.f("ix_items_id"), "items", ["id"], unique=False)
    op.create_index(op.f("ix_items_sku"), "items", ["sku"], unique=False)
    op.create_index(op.f("ix_items_workspace_id"), "items", ["workspace_id"], unique=False)
    op.create_table(
        "suppliers",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_suppliers_id"), "suppliers", ["id"], unique=False)
    op.create_index(op.f("ix_suppliers_workspace_id"), "suppliers", ["workspace_id"], unique=False)
    op.create_table(
        "inventory",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("quantity_available", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_inventory_id"), "inventory", ["id"], unique=False)
    op.create_index(op.f("ix_inventory_item_id"), "inventory", ["item_id"], unique=True)
    op.create_index(op.f("ix_inventory_workspace_id"), "inventory", ["workspace_id"], unique=False)
    op.create_table(
        "inventory_stock_movements",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("quantity_change", sa.Integer(), nullable=False),
        sa.Column(
            "reference_type",
            sa.Enum("SELL_ORDER", "PURCHASE_ORDER", "MANUAL_ADJUSTMENT", name="ordertype"),
            nullable=False,
        ),
        sa.Column("reference_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_inventory_stock_movements_id"), "inventory_stock_movements", ["id"], unique=False)
    op.create_index(
        op.f("ix_inventory_stock_movements_item_id"), "inventory_stock_movements", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_stock_movements_reference_id"), "inventory_stock_movements", ["reference_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_stock_movements_workspace_id"), "inventory_stock_movements", ["workspace_id"], unique=False
    )
    op.create_table(
        "purchase_orders",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=True),
        sa.Column("po_number", sa.String(length=100), nullable=False),
        sa.Column("total_amount", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_purchase_orders_id"), "purchase_orders", ["id"], unique=False)
    op.create_index(op.f("ix_purchase_orders_po_number"), "purchase_orders", ["po_number"], unique=False)
    op.create_index(op.f("ix_purchase_orders_supplier_id"), "purchase_orders", ["supplier_id"], unique=False)
    op.create_index(op.f("ix_purchase_orders_workspace_id"), "purchase_orders", ["workspace_id"], unique=False)
    op.create_table(
        "sell_orders",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("order_number", sa.String(length=100), nullable=False),
        sa.Column("total_amount", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sell_orders_customer_id"), "sell_orders", ["customer_id"], unique=False)
    op.create_index(op.f("ix_sell_orders_id"), "sell_orders", ["id"], unique=False)
    op.create_index(op.f("ix_sell_orders_order_number"), "sell_orders", ["order_number"], unique=False)
    op.create_index(op.f("ix_sell_orders_workspace_id"), "sell_orders", ["workspace_id"], unique=False)
    op.create_table(
        "purchase_order_lines",
        sa.Column("purchase_order_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_cost", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_purchase_order_lines_id"), "purchase_order_lines", ["id"], unique=False)
    op.create_index(op.f("ix_purchase_order_lines_item_id"), "purchase_order_lines", ["item_id"], unique=False)
    op.create_index(
        op.f("ix_purchase_order_lines_purchase_order_id"), "purchase_order_lines", ["purchase_order_id"], unique=False
    )
    op.create_table(
        "sell_order_lines",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["sell_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sell_order_lines_id"), "sell_order_lines", ["id"], unique=False)
    op.create_index(op.f("ix_sell_order_lines_item_id"), "sell_order_lines", ["item_id"], unique=False)
    op.create_index(op.f("ix_sell_order_lines_order_id"), "sell_order_lines", ["order_id"], unique=False)
    op.add_column("ebay_items", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f("ebay_items_workspace_id_fkey"), "ebay_items", type_="foreignkey")
    op.create_foreign_key(None, "ebay_items", "workspaces", ["workspace_id"], ["id"])
    op.add_column("pricing_plans", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("pricing_subscriptions", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("pricing_usage", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("user_sessions", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("workspace_integrations", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f("workspace_integrations_workspace_id_fkey"), "workspace_integrations", type_="foreignkey")
    op.create_foreign_key(None, "workspace_integrations", "workspaces", ["workspace_id"], ["id"])
    op.add_column("workspace_users", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f("workspace_users_user_id_fkey"), "workspace_users", type_="foreignkey")
    op.drop_constraint(op.f("workspace_users_workspace_id_fkey"), "workspace_users", type_="foreignkey")
    op.create_foreign_key(None, "workspace_users", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "workspace_users", "workspaces", ["workspace_id"], ["id"])
    op.add_column("workspaces", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspaces", "deleted_at")
    op.drop_constraint(None, "workspace_users", type_="foreignkey")
    op.drop_constraint(None, "workspace_users", type_="foreignkey")
    op.create_foreign_key(
        op.f("workspace_users_workspace_id_fkey"),
        "workspace_users",
        "workspaces",
        ["workspace_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("workspace_users_user_id_fkey"), "workspace_users", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("workspace_users", "deleted_at")
    op.drop_constraint(None, "workspace_integrations", type_="foreignkey")
    op.create_foreign_key(
        op.f("workspace_integrations_workspace_id_fkey"),
        "workspace_integrations",
        "workspaces",
        ["workspace_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("workspace_integrations", "deleted_at")
    op.drop_column("users", "deleted_at")
    op.drop_column("user_sessions", "deleted_at")
    op.drop_column("pricing_usage", "deleted_at")
    op.drop_column("pricing_subscriptions", "deleted_at")
    op.drop_column("pricing_plans", "deleted_at")
    op.drop_constraint(None, "ebay_items", type_="foreignkey")
    op.create_foreign_key(
        op.f("ebay_items_workspace_id_fkey"), "ebay_items", "workspaces", ["workspace_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("ebay_items", "deleted_at")
    op.drop_index(op.f("ix_sell_order_lines_order_id"), table_name="sell_order_lines")
    op.drop_index(op.f("ix_sell_order_lines_item_id"), table_name="sell_order_lines")
    op.drop_index(op.f("ix_sell_order_lines_id"), table_name="sell_order_lines")
    op.drop_table("sell_order_lines")
    op.drop_index(op.f("ix_purchase_order_lines_purchase_order_id"), table_name="purchase_order_lines")
    op.drop_index(op.f("ix_purchase_order_lines_item_id"), table_name="purchase_order_lines")
    op.drop_index(op.f("ix_purchase_order_lines_id"), table_name="purchase_order_lines")
    op.drop_table("purchase_order_lines")
    op.drop_index(op.f("ix_sell_orders_workspace_id"), table_name="sell_orders")
    op.drop_index(op.f("ix_sell_orders_order_number"), table_name="sell_orders")
    op.drop_index(op.f("ix_sell_orders_id"), table_name="sell_orders")
    op.drop_index(op.f("ix_sell_orders_customer_id"), table_name="sell_orders")
    op.drop_table("sell_orders")
    op.drop_index(op.f("ix_purchase_orders_workspace_id"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_supplier_id"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_po_number"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_id"), table_name="purchase_orders")
    op.drop_table("purchase_orders")
    op.drop_index(op.f("ix_inventory_stock_movements_workspace_id"), table_name="inventory_stock_movements")
    op.drop_index(op.f("ix_inventory_stock_movements_reference_id"), table_name="inventory_stock_movements")
    op.drop_index(op.f("ix_inventory_stock_movements_item_id"), table_name="inventory_stock_movements")
    op.drop_index(op.f("ix_inventory_stock_movements_id"), table_name="inventory_stock_movements")
    op.drop_table("inventory_stock_movements")
    op.drop_index(op.f("ix_inventory_workspace_id"), table_name="inventory")
    op.drop_index(op.f("ix_inventory_item_id"), table_name="inventory")
    op.drop_index(op.f("ix_inventory_id"), table_name="inventory")
    op.drop_table("inventory")
    op.drop_index(op.f("ix_suppliers_workspace_id"), table_name="suppliers")
    op.drop_index(op.f("ix_suppliers_id"), table_name="suppliers")
    op.drop_table("suppliers")
    op.drop_index(op.f("ix_items_workspace_id"), table_name="items")
    op.drop_index(op.f("ix_items_sku"), table_name="items")
    op.drop_index(op.f("ix_items_id"), table_name="items")
    op.drop_table("items")
    op.drop_index(op.f("ix_customers_workspace_id"), table_name="customers")
    op.drop_index(op.f("ix_customers_id"), table_name="customers")
    op.drop_index(op.f("ix_customers_email"), table_name="customers")
    op.drop_table("customers")
    # ### end Alembic commands ###
