"""empty message

Revision ID: 46ae36c51a95
Revises: 
Create Date: 2026-04-13 22:35:23.464790

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '46ae36c51a95'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebay_items',
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', 'OUT_OF_STOCK', 'DRAFT', name='ebayitemstatus', native_enum=False, length=50), nullable=False),
    sa.Column('images', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ebay_items_external_id'), 'ebay_items', ['external_id'], unique=True)
    op.create_index(op.f('ix_ebay_items_id'), 'ebay_items', ['id'], unique=False)
    op.create_index(op.f('ix_ebay_items_sku'), 'ebay_items', ['sku'], unique=False)
    op.create_index(op.f('ix_ebay_items_status'), 'ebay_items', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ebay_items_status'), table_name='ebay_items')
    op.drop_index(op.f('ix_ebay_items_sku'), table_name='ebay_items')
    op.drop_index(op.f('ix_ebay_items_id'), table_name='ebay_items')
    op.drop_index(op.f('ix_ebay_items_external_id'), table_name='ebay_items')
    op.drop_table('ebay_items')
    # ### end Alembic commands ###
