"""SupplierUser model added

Revision ID: 6b9cb8802969
Revises: b9ba1eef7fa2
Create Date: 2026-05-19 21:48:37.578341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b9cb8802969'
down_revision: Union[str, Sequence[str], None] = 'b9ba1eef7fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_users',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_users_id'), 'supplier_users', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_users_supplier_id'), 'supplier_users', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_users_supplier_id'), table_name='supplier_users')
    op.drop_index(op.f('ix_supplier_users_id'), table_name='supplier_users')
    op.drop_table('supplier_users')
    # ### end Alembic commands ###
