"""Add Role, Status in WorkspaceUser model

Revision ID: 8f69186186f4
Revises: 95f5a2ebf883
Create Date: 2026-05-23 02:05:55.058044

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f69186186f4"
down_revision: str | Sequence[str] | None = "95f5a2ebf883"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "hashed_password", existing_type=sa.VARCHAR(), nullable=True)
    op.add_column(
        "workspace_users",
        sa.Column(
            "role",
            sa.Enum("FULL_ADMIN", "EDIT_ONLY", "READ_ONLY", name="workspaceroleenum", native_enum=False),
            server_default="read_only",
            nullable=False,
        ),
    )
    op.add_column(
        "workspace_users",
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "PENDING", name="invitationstatusenum", native_enum=False),
            server_default="pending",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace_users", "status")
    op.drop_column("workspace_users", "role")
    op.alter_column("users", "hashed_password", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
