"""initial migration

Revision ID: 95f5a2ebf883
Revises:
Create Date: 2026-05-22 15:33:39.790204

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "95f5a2ebf883"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "workspaces",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workspaces_email"), "workspaces", ["email"], unique=True)
    op.create_index(op.f("ix_workspaces_id"), "workspaces", ["id"], unique=False)
    op.create_table(
        "ebay_items",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("sku", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ENDED", "OUT_OF_STOCK", "DRAFT", name="ebayitemstatus", native_enum=False, length=50),
            nullable=False,
        ),
        sa.Column("images", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "external_id", name="uq_workspace_ebay_external_id"),
    )
    op.create_index(op.f("ix_ebay_items_external_id"), "ebay_items", ["external_id"], unique=False)
    op.create_index(op.f("ix_ebay_items_id"), "ebay_items", ["id"], unique=False)
    op.create_index(op.f("ix_ebay_items_sku"), "ebay_items", ["sku"], unique=False)
    op.create_index(op.f("ix_ebay_items_status"), "ebay_items", ["status"], unique=False)
    op.create_index(op.f("ix_ebay_items_workspace_id"), "ebay_items", ["workspace_id"], unique=False)
    op.create_table(
        "user_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_sessions_id"), "user_sessions", ["id"], unique=False)
    op.create_index(op.f("ix_user_sessions_session_id"), "user_sessions", ["session_id"], unique=True)
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    op.create_table(
        "workspace_integrations",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("provider_type", sa.String(length=50), nullable=False),
        sa.Column("credentials", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "provider_type", name="uq_workspace_provider"),
    )
    op.create_index(op.f("ix_workspace_integrations_id"), "workspace_integrations", ["id"], unique=False)
    op.create_index(
        op.f("ix_workspace_integrations_workspace_id"), "workspace_integrations", ["workspace_id"], unique=False
    )
    op.create_table(
        "workspace_users",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "workspace_id", name="uq_workspace_and_user"),
    )
    op.create_index(op.f("ix_workspace_users_id"), "workspace_users", ["id"], unique=False)
    op.create_index(op.f("ix_workspace_users_user_id"), "workspace_users", ["user_id"], unique=False)
    op.create_index(op.f("ix_workspace_users_workspace_id"), "workspace_users", ["workspace_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workspace_users_workspace_id"), table_name="workspace_users")
    op.drop_index(op.f("ix_workspace_users_user_id"), table_name="workspace_users")
    op.drop_index(op.f("ix_workspace_users_id"), table_name="workspace_users")
    op.drop_table("workspace_users")
    op.drop_index(op.f("ix_workspace_integrations_workspace_id"), table_name="workspace_integrations")
    op.drop_index(op.f("ix_workspace_integrations_id"), table_name="workspace_integrations")
    op.drop_table("workspace_integrations")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_session_id"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_id"), table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index(op.f("ix_ebay_items_workspace_id"), table_name="ebay_items")
    op.drop_index(op.f("ix_ebay_items_status"), table_name="ebay_items")
    op.drop_index(op.f("ix_ebay_items_sku"), table_name="ebay_items")
    op.drop_index(op.f("ix_ebay_items_id"), table_name="ebay_items")
    op.drop_index(op.f("ix_ebay_items_external_id"), table_name="ebay_items")
    op.drop_table("ebay_items")
    op.drop_index(op.f("ix_workspaces_id"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_email"), table_name="workspaces")
    op.drop_table("workspaces")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
