"""EbayIntegration model added.

Revision ID: 9b04dbfeebf0
Revises: b32ca9ab543f
Create Date: 2026-05-19 21:51:03.844705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b04dbfeebf0'
down_revision: Union[str, Sequence[str], None] = 'b32ca9ab543f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebay_integrations',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_account_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ebay_integrations_id'), 'ebay_integrations', ['id'], unique=False)
    op.create_index(op.f('ix_ebay_integrations_supplier_id'), 'ebay_integrations', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ebay_integrations_supplier_id'), table_name='ebay_integrations')
    op.drop_index(op.f('ix_ebay_integrations_id'), table_name='ebay_integrations')
    op.drop_table('ebay_integrations')
    # ### end Alembic commands ###
