"""Location fields added in Workspace model

Revision ID: a3a04c15950b
Revises: ec1acef0d7f3
Create Date: 2026-06-07 01:12:11.704270

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a3a04c15950b"
down_revision: Union[str, Sequence[str], None] = "ec1acef0d7f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workspaces", sa.Column("phone_number", sa.String(length=20), nullable=True))
    op.add_column("workspaces", sa.Column("country", sa.String(length=100), nullable=True))
    op.add_column("workspaces", sa.Column("city", sa.String(length=100), nullable=True))
    op.add_column("workspaces", sa.Column("address_line1", sa.String(length=255), nullable=True))
    op.add_column("workspaces", sa.Column("address_line2", sa.String(length=255), nullable=True))
    op.add_column("workspaces", sa.Column("postal_code", sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, "workspaces", ["phone_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workspaces", type_="unique")
    op.drop_column("workspaces", "postal_code")
    op.drop_column("workspaces", "address_line2")
    op.drop_column("workspaces", "address_line1")
    op.drop_column("workspaces", "city")
    op.drop_column("workspaces", "country")
    op.drop_column("workspaces", "phone_number")
    # ### end Alembic commands ###
