"""User model added

Revision ID: b32ca9ab543f
Revises: 6b9cb8802969
Create Date: 2026-05-19 21:49:34.530513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32ca9ab543f'
down_revision: Union[str, Sequence[str], None] = '6b9cb8802969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('supplier_users', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_supplier_users_user_id'), 'supplier_users', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_supplier', 'supplier_users', ['user_id', 'supplier_id'])
    op.create_foreign_key(None, 'supplier_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplier_users', type_='foreignkey')
    op.drop_constraint('uq_user_supplier', 'supplier_users', type_='unique')
    op.drop_index(op.f('ix_supplier_users_user_id'), table_name='supplier_users')
    op.drop_column('supplier_users', 'user_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
