"""EbayItem model added.

Revision ID: e028ae5fef3b
Revises: f186b554bce8
Create Date: 2026-05-19 21:56:22.701070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e028ae5fef3b'
down_revision: Union[str, Sequence[str], None] = 'f186b554bce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebay_items',
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', 'OUT_OF_STOCK', 'DRAFT', name='ebayitemstatus', native_enum=False, length=50), nullable=False),
    sa.Column('images', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ebay_items_external_id'), 'ebay_items', ['external_id'], unique=True)
    op.create_index(op.f('ix_ebay_items_id'), 'ebay_items', ['id'], unique=False)
    op.create_index(op.f('ix_ebay_items_sku'), 'ebay_items', ['sku'], unique=False)
    op.create_index(op.f('ix_ebay_items_status'), 'ebay_items', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ebay_items_status'), table_name='ebay_items')
    op.drop_index(op.f('ix_ebay_items_sku'), table_name='ebay_items')
    op.drop_index(op.f('ix_ebay_items_id'), table_name='ebay_items')
    op.drop_index(op.f('ix_ebay_items_external_id'), table_name='ebay_items')
    op.drop_table('ebay_items')
    # ### end Alembic commands ###
