"""Fix Role, Status in WorkspaceUser model

Revision ID: ec1acef0d7f3
Revises: 8f69186186f4
Create Date: 2026-05-23 02:14:04.634057

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'ec1acef0d7f3'
down_revision: str | Sequence[str] | None = '8f69186186f4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
