"""EbayIntegrationUser model added.

Revision ID: f186b554bce8
Revises: 9b04dbfeebf0
Create Date: 2026-05-19 21:52:21.697272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f186b554bce8'
down_revision: Union[str, Sequence[str], None] = '9b04dbfeebf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebay_integration_users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('ebay_integration_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('FULL_ADMIN', 'EDITOR', 'READER', name='permission_role_enum'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ebay_integration_id'], ['ebay_integrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'supplier_id'], ['supplier_users.user_id', 'supplier_users.supplier_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ebay_integration_id', name='uq_user_ebay_integration')
    )
    op.create_index(op.f('ix_ebay_integration_users_ebay_integration_id'), 'ebay_integration_users', ['ebay_integration_id'], unique=False)
    op.create_index(op.f('ix_ebay_integration_users_id'), 'ebay_integration_users', ['id'], unique=False)
    op.create_index(op.f('ix_ebay_integration_users_supplier_id'), 'ebay_integration_users', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_ebay_integration_users_user_id'), 'ebay_integration_users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ebay_integration_users_user_id'), table_name='ebay_integration_users')
    op.drop_index(op.f('ix_ebay_integration_users_supplier_id'), table_name='ebay_integration_users')
    op.drop_index(op.f('ix_ebay_integration_users_id'), table_name='ebay_integration_users')
    op.drop_index(op.f('ix_ebay_integration_users_ebay_integration_id'), table_name='ebay_integration_users')
    op.drop_table('ebay_integration_users')
    # ### end Alembic commands ###
